# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Pull Requests for Tomorrow
tagline:             "Jamie Kang's weblog on building recent computing systems"
description:         "Jamie Kang's weblog on building recent computing systems."
url:                 ''
baseurl:             ''
gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# About/contact
author:
  name:              Jiyang "Jamie" Kang
  url:               https://twitter.com/jiyangkang
  email:             jiyangkang@gmail.com

# Custom vars
version:             1.0.0

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:
  ua: 'UA-98577553-1'
# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed

# Jekyll 3 now only supports Kramdown for Markdown
markdown:            kramdown
kramdown:
  math_engine: mathjax
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'